// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file is auto-generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2'. Do not edit.</auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions.Incubating;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class DeploymentAttributes
{
    /// <summary>
    /// Deprecated, use <c>deployment.environment.name</c> instead.
    /// </summary>
    [Obsolete("Replaced by <c>deployment.environment.name</c>.")]
    public const string AttributeDeploymentEnvironment = "deployment.environment";

    /// <summary>
    /// The id of the deployment.
    /// </summary>
    public const string AttributeDeploymentId = "deployment.id";

    /// <summary>
    /// The name of the deployment.
    /// </summary>
    public const string AttributeDeploymentName = "deployment.name";

    /// <summary>
    /// The status of the deployment.
    /// </summary>
    public const string AttributeDeploymentStatus = "deployment.status";

    /// <summary>
    /// The status of the deployment.
    /// </summary>
    public static class DeploymentStatusValues
    {
        /// <summary>
        /// failed.
        /// </summary>
        public const string Failed = "failed";

        /// <summary>
        /// succeeded.
        /// </summary>
        public const string Succeeded = "succeeded";
    }
}
