<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- OmniSharp/VS Code requires TargetFrameworks to be in descending order for IntelliSense and analysis. -->
    <TargetFrameworks>$(SupportedNetTargets)</TargetFrameworks>
    <TargetFrameworks Condition="$(OS) == 'Windows_NT'">$(TargetFrameworks);$(NetFrameworkMinimumSupportedVersion)</TargetFrameworks>
    <Description>Fuzz test project for OpenTelemetry Dynamic Control.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenTelemetry.DynamicControl\OpenTelemetry.DynamicControl.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETFramework'">
    <PackageReference Include="System.Memory" VersionOverride="4.6.3" />
  </ItemGroup>

</Project>
