codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**.md"
  - "src/Shared" # copied from main OTel project and has code coverage there
  - "test"
  - "examples"
  - "build"
  - ".github"
  - ".vscode"

flags:
  unittests-Solution:
    carryforward: true
    paths:
      - src

  unittests-Exporter.Geneva:
    carryforward: true
    paths:
      - src/OpenTelemetry.Exporter.Geneva

  unittests-Exporter.OneCollector:
    carryforward: true
    paths:
      - src/OpenTelemetry.Exporter.OneCollector

  unittests-Extensions:
    carryforward: true
    paths:
      - src/OpenTelemetry.Extensions

  unittests-Instrumentation.AspNet:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.AspNet
      - src/OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule

  unittests-Instrumentation.AspNetCore:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.AspNetCore

  unittests-Instrumentation.EventCounters:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.EventCounters

  unittests-Instrumentation.Http:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Http

  unittests-Instrumentation.GrpcNetClient:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.GrpcNetClient

  unittests-Instrumentation.Owin:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Owin

  unittests-Instrumentation.Process:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Process

  unittests-Instrumentation.Runtime:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Runtime

  unittests-Instrumentation.SqlClient:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.SqlClient

  unittests-Instrumentation.StackExchangeRedis:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.StackExchangeRedis

  unittests-Instrumentation.Wcf:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Wcf

  unittests-PersistentStorage:
    carryforward: true
    paths:
      - src/OpenTelemetry.PersistentStorage.Abstractions
      - src/OpenTelemetry.PersistentStorage.FileSystem

  unittests-Resources.Azure:
    carryforward: true
    paths:
      - src/OpenTelemetry.Resources.Azure

  unittests-Resources.Gcp:
    carryforward: true
    paths:
      - src/OpenTelemetry.Resources.Gcp

  unittests-Resources.Host:
    carryforward: true
    paths:
      - src/OpenTelemetry.Resources.Host

  unittests-Resources.Process:
    carryforward: true
    paths:
      - src/OpenTelemetry.Resources.Process

  unittests-Resources.ProcessRuntime:
    carryforward: true
    paths:
      - src/OpenTelemetry.Resources.ProcessRuntime

  unittests-SemanticConventions:
    carryforward: true
    paths:
      - src/OpenTelemetry.SemanticConventions
