codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**.md"
  - "src/OpenTelemetry.Contrib.Shared"  # copied from main OTel project and has code coverage there
  - "test/**/*"
