codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project: off
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*.md"
  - "src/Shared"  # copied from main OTel project and has code coverage there
  - "test"
  - "examples"
  - "build"

flags:
  unittests:
    carryforward: true
    paths:
      - src

  unittests-Exporter.Geneva:
    carryforward: true
    paths:
      - src/OpenTelemetry.Exporter.Geneva

  unittests-Exporter.OneCollector:
    carryforward: true
    paths:
      - src/OpenTelemetry.Exporter.OneCollector

  unittests-Instrumentation.Process:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Process

  unittests-Instrumentation.Wcf:
    carryforward: true
    paths:
      - src/OpenTelemetry.Instrumentation.Wcf

