# This file is used by .github/workflows/assign-reviewers.yml

# Each component identified by its path prefix has a list of users
# Please add the entries in alphabetically sorted order
components:
  src/OpenTelemetry.Exporter.Geneva/:
    - cijothomas
    - codeblanch
    - reyang
    - utpilla
    - Yun-Ting
  src/OpenTelemetry.Exporter.InfluxDB/:
    - havret
  src/OpenTelemetry.Exporter.Instana/:
    - zivaninstana
  src/OpenTelemetry.Exporter.OneCollector/:
    - codeblanch
    - reyang
  src/OpenTelemetry.Exporter.Stackdriver/:
    - SergeyKanzhelev
  src/OpenTelemetry.Extensions/:
    - codeblanch
  src/OpenTelemetry.Extensions.AWS/:
    - srprash
    - atshaw43
  src/OpenTelemetry.Extensions.Enrichment/:
    - xakep139
  src/OpenTelemetry.Instrumentation.AWS/:
    - srprash
    - atshaw43
  src/OpenTelemetry.Instrumentation.AWSLambda/:
    - rypdal
    - Oberon00
  src/OpenTelemetry.Instrumentation.Cassandra/:
    - xsoheilalizadeh
  src/OpenTelemetry.Instrumentation.ElasticsearchClient/:
    - ejsmith
  src/OpenTelemetry.Instrumentation.EventCounters/:
    - hananiel
    - mic-max
  src/OpenTelemetry.Instrumentation.GrpcCore/:
    - pcwiese
  src/OpenTelemetry.Instrumentation.Hangfire/:
    - fred2u
  src/OpenTelemetry.Instrumentation.Owin/:
    - codeblanch
  src/OpenTelemetry.Instrumentation.Process/:
    - Yun-Ting
  src/OpenTelemetry.Instrumentation.Quartz/:
    - maldago
  src/OpenTelemetry.Instrumentation.Runtime/:
    - twenzel
    - xiang17
  src/OpenTelemetry.Instrumentation.Wcf/:
    - codeblanch
  src/OpenTelemetry.PersistentStorage.Abstractions/:
    - vishweshbankwar
  src/OpenTelemetry.PersistentStorage.FileSystem/:
    - vishweshbankwar
  src/OpenTelemetry.ResourceDetectors.AWS/:
    - srprash
    - atshaw43
  src/OpenTelemetry.ResourceDetectors.Azure/:
    - rajkumar-rangaraj
    - vishweshbankwar
  src/OpenTelemetry.ResourceDetectors.Container/:
    - iskiselev
  src/OpenTelemetry.Sampler.AWS/:
    - srprash
    - atshaw43
  test/OpenTelemetry.Exporter.Geneva.Benchmark/:
    - cijothomas
    - codeblanch
    - reyang
    - utpilla
    - Yun-Ting
  test/OpenTelemetry.Exporter.Geneva.Stress/:
    - cijothomas
    - codeblanch
    - reyang
    - utpilla
    - Yun-Ting
  test/OpenTelemetry.Exporter.Geneva.Tests/:
    - cijothomas
    - codeblanch
    - reyang
    - utpilla
    - Yun-Ting
  test/OpenTelemetry.Exporter.InfluxDB.Tests/:
    - havret
  test/OpenTelemetry.Exporter.Instana.Tests/:
    - zivaninstana
  test/OpenTelemetry.Exporter.OneCollector.Benchmarks/:
    - codeblanch
    - reyang
  test/OpenTelemetry.Exporter.OneCollector.Tests/:
    - codeblanch
    - reyang
  test/OpenTelemetry.Exporter.Stackdriver.Tests/:
    - SergeyKanzhelev
  test/OpenTelemetry.Extensions.Tests/:
    - codeblanch
  test/OpenTelemetry.Extensions.AWS.Tests/:
    - srprash
    - atshaw43
  test/OpenTelemetry.Extensions.Enrichment.Tests/:
    - xakep139
  test/OpenTelemetry.Instrumentation.AWS.Tests/:
    - srprash
    - atshaw43
  test/OpenTelemetry.Instrumentation.AWSLambda.Tests/:
    - rypdal
    - Oberon00
  test/OpenTelemetry.Instrumentation.Cassandra.Tests/:
    - xsoheilalizadeh
  test/OpenTelemetry.Instrumentation.ElasticsearchClient.Tests/:
    - ejsmith
  test/OpenTelemetry.Instrumentation.EventCounters.Tests/:
    - hananiel
    - mic-max
  test/OpenTelemetry.Instrumentation.GrpcCore.Tests/:
    - pcwiese
  test/OpenTelemetry.Instrumentation.Hangfire.Tests/:
    - fred2u
  test/OpenTelemetry.Instrumentation.Owin.Tests/:
    - codeblanch
  test/OpenTelemetry.Instrumentation.Quartz.Tests/:
    - maldago
  test/OpenTelemetry.Instrumentation.Runtime.Tests/:
    - twenzel
    - xiang17
  test/OpenTelemetry.Instrumentation.Wcf.Tests/:
    - codeblanch
  test/OpenTelemetry.PersistentStorage.FileSystem.Tests/:
    - vishweshbankwar
  test/OpenTelemetry.ResourceDetectors.AWS.Tests/:
    - srprash
    - atshaw43
  test/OpenTelemetry.ResourceDetectors.Azure.Tests/:
    - rajkumar-rangaraj
    - vishweshbankwar
  test/OpenTelemetry.ResourceDetectors.Container.Tests/:
    - iskiselev
  test/OpenTelemetry.Sampler.AWS.Tests/:
    - srprash
    - atshaw43
