version: 2
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the nuget registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          dependency_name: "OpenTelemetry"