// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from scripts/templates/SemanticConventionsAttributes.cs.j2</auto-generated>

#pragma warning disable CS1570 // XML comment has badly formed XML

using System;

namespace OpenTelemetry.SemanticConventions
{
    /// <summary>
    /// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
    /// </summary>
    public static class WebengineAttributes
    {
        /// <summary>
        /// Additional description of the web engine (e.g. detailed version and edition information).
        /// </summary>
        public const string AttributeWebengineDescription = "webengine.description";

        /// <summary>
        /// The name of the web engine.
        /// </summary>
        public const string AttributeWebengineName = "webengine.name";

        /// <summary>
        /// The version of the web engine.
        /// </summary>
        public const string AttributeWebengineVersion = "webengine.version";
    }
}
