<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(SupportedNetTargets)</TargetFrameworks>
    <TargetFrameworks Condition="$(OS) == 'Windows_NT'">$(TargetFrameworks);$(NetFrameworkMinimumSupportedVersion)</TargetFrameworks>
    <Description>Unit test project for OpenTelemetry Dynamic Control.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenTelemetry.DynamicControl\OpenTelemetry.DynamicControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(RepoRoot)\test\Shared\InMemoryEventListener.cs" Link="Includes\InMemoryEventListener.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$([MSBuild]::GetTargetFrameworkIdentifier(`$(TargetFramework)`))' == '.NETFramework'">
    <PackageReference Include="System.Memory" VersionOverride="4.6.3" />
  </ItemGroup>

</Project>
