// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class AppAttributes
{
    /// <summary>
    /// A unique identifier representing the installation of an application on a specific device.
    /// </summary>
    /// <remarks>
    /// Its value SHOULD persist across launches of the same application installation, including through application upgrades.
    /// It SHOULD change if the application is uninstalled or if all applications of the vendor are uninstalled.
    /// Additionally, users might be able to reset this value (e.g. by clearing application data).
    /// If an app is installed multiple times on the same device (e.g. in different accounts on Android), each <c>app.installation.id</c> SHOULD have a different value.
    /// If multiple OpenTelemetry SDKs are used within the same application, they SHOULD use the same value for <c>app.installation.id</c>.
    /// Hardware IDs (e.g. serial number, IMEI, MAC address) MUST NOT be used as the <c>app.installation.id</c>.
    /// <p>
    /// For iOS, this value SHOULD be equal to the <a href="https://developer.apple.com/documentation/uikit/uidevice/identifierforvendor">vendor identifier</a>.
    /// <p>
    /// For Android, examples of <c>app.installation.id</c> implementations include:
    /// <ul>
    ///   <li><a href="https://firebase.google.com/docs/projects/manage-installations">Firebase Installation ID</a>.</li>
    ///   <li>A globally unique UUID which is persisted across sessions in your application.</li>
    ///   <li><a href="https://developer.android.com/identity/app-set-id">App set ID</a>.</li>
    ///   <li><a href="https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID"><c>Settings.getString(Settings.Secure.ANDROID_ID)</c></a>.</li>
    /// </ul>
    /// <p>
    /// More information about Android identifier best practices can be found <a href="https://developer.android.com/training/articles/user-data-ids">here</a>.
    /// </remarks>
    public const string AttributeAppInstallationId = "app.installation.id";

    /// <summary>
    /// The x (horizontal) coordinate of a screen coordinate, in screen pixels.
    /// </summary>
    public const string AttributeAppScreenCoordinateX = "app.screen.coordinate.x";

    /// <summary>
    /// The y (vertical) component of a screen coordinate, in screen pixels.
    /// </summary>
    public const string AttributeAppScreenCoordinateY = "app.screen.coordinate.y";

    /// <summary>
    /// An identifier that uniquely differentiates this widget from other widgets in the same application.
    /// </summary>
    /// <remarks>
    /// A widget is an application component, typically an on-screen visual GUI element.
    /// </remarks>
    public const string AttributeAppWidgetId = "app.widget.id";

    /// <summary>
    /// The name of an application widget.
    /// </summary>
    /// <remarks>
    /// A widget is an application component, typically an on-screen visual GUI element.
    /// </remarks>
    public const string AttributeAppWidgetName = "app.widget.name";
}
