// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class AzureAttributes
{
    /// <summary>
    /// The unique identifier of the client instance.
    /// </summary>
    public const string AttributeAzureClientId = "azure.client.id";

    /// <summary>
    /// Cosmos client connection mode.
    /// </summary>
    public const string AttributeAzureCosmosdbConnectionMode = "azure.cosmosdb.connection.mode";

    /// <summary>
    /// Account or request <a href="https://learn.microsoft.com/azure/cosmos-db/consistency-levels">consistency level</a>.
    /// </summary>
    public const string AttributeAzureCosmosdbConsistencyLevel = "azure.cosmosdb.consistency.level";

    /// <summary>
    /// List of regions contacted during operation in the order that they were contacted. If there is more than one region listed, it indicates that the operation was performed on multiple regions i.e. cross-regional call.
    /// </summary>
    /// <remarks>
    /// Region name matches the format of <c>displayName</c> in <a href="https://learn.microsoft.com/rest/api/resources/subscriptions/list-locations">Azure Location API</a>.
    /// </remarks>
    public const string AttributeAzureCosmosdbOperationContactedRegions = "azure.cosmosdb.operation.contacted_regions";

    /// <summary>
    /// The number of request units consumed by the operation.
    /// </summary>
    public const string AttributeAzureCosmosdbOperationRequestCharge = "azure.cosmosdb.operation.request_charge";

    /// <summary>
    /// Request payload size in bytes.
    /// </summary>
    public const string AttributeAzureCosmosdbRequestBodySize = "azure.cosmosdb.request.body.size";

    /// <summary>
    /// Cosmos DB sub status code.
    /// </summary>
    public const string AttributeAzureCosmosdbResponseSubStatusCode = "azure.cosmosdb.response.sub_status_code";

    /// <summary>
    /// <a href="https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers">Azure Resource Provider Namespace</a> as recognized by the client.
    /// </summary>
    public const string AttributeAzureResourceProviderNamespace = "azure.resource_provider.namespace";

    /// <summary>
    /// The unique identifier of the service request. It's generated by the Azure service and returned with the response.
    /// </summary>
    public const string AttributeAzureServiceRequestId = "azure.service.request.id";

    /// <summary>
    /// Cosmos client connection mode.
    /// </summary>
    public static class AzureCosmosdbConnectionModeValues
    {
        /// <summary>
        /// Gateway (HTTP) connection.
        /// </summary>
        public const string Gateway = "gateway";

        /// <summary>
        /// Direct connection.
        /// </summary>
        public const string Direct = "direct";
    }

    /// <summary>
    /// Account or request <a href="https://learn.microsoft.com/azure/cosmos-db/consistency-levels">consistency level</a>.
    /// </summary>
    public static class AzureCosmosdbConsistencyLevelValues
    {
        /// <summary>
        /// Strong.
        /// </summary>
        public const string Strong = "Strong";

        /// <summary>
        /// Bounded Staleness.
        /// </summary>
        public const string BoundedStaleness = "BoundedStaleness";

        /// <summary>
        /// Session.
        /// </summary>
        public const string Session = "Session";

        /// <summary>
        /// Eventual.
        /// </summary>
        public const string Eventual = "Eventual";

        /// <summary>
        /// Consistent Prefix.
        /// </summary>
        public const string ConsistentPrefix = "ConsistentPrefix";
    }
}
