// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class DeviceAttributes
{
    /// <summary>
    /// A unique identifier representing the device.
    /// </summary>
    /// <remarks>
    /// Its value SHOULD be identical for all apps on a device and it SHOULD NOT change if an app is uninstalled and re-installed.
    /// However, it might be resettable by the user for all apps on a device.
    /// Hardware IDs (e.g. vendor-specific serial number, IMEI or MAC address) MAY be used as values.
    /// <p>
    /// More information about Android identifier best practices can be found <a href="https://developer.android.com/training/articles/user-data-ids">here</a>.
    /// <blockquote>
    /// [!WARNING]
    /// <p>
    /// This attribute may contain sensitive (PII) information. Caution should be taken when storing personal data or anything which can identify a user. GDPR and data protection laws may apply,
    /// ensure you do your own due diligence.
    /// <p>
    /// Due to these reasons, this identifier is not recommended for consumer applications and will likely result in rejection from both Google Play and App Store.
    /// However, it may be appropriate for specific enterprise scenarios, such as kiosk devices or enterprise-managed devices, with appropriate compliance clearance.
    /// Any instrumentation providing this identifier MUST implement it as an opt-in feature.
    /// <p>
    /// See <a href="/docs/attributes-registry/app.md#app-installation-id"><c>app.installation.id</c></a> for a more privacy-preserving alternative.</blockquote>
    /// </remarks>
    public const string AttributeDeviceId = "device.id";

    /// <summary>
    /// The name of the device manufacturer.
    /// </summary>
    /// <remarks>
    /// The Android OS provides this field via <a href="https://developer.android.com/reference/android/os/Build#MANUFACTURER">Build</a>. iOS apps SHOULD hardcode the value <c>Apple</c>.
    /// </remarks>
    public const string AttributeDeviceManufacturer = "device.manufacturer";

    /// <summary>
    /// The model identifier for the device.
    /// </summary>
    /// <remarks>
    /// It's recommended this value represents a machine-readable version of the model identifier rather than the market or consumer-friendly name of the device.
    /// </remarks>
    public const string AttributeDeviceModelIdentifier = "device.model.identifier";

    /// <summary>
    /// The marketing name for the device model.
    /// </summary>
    /// <remarks>
    /// It's recommended this value represents a human-readable version of the device model rather than a machine-readable alternative.
    /// </remarks>
    public const string AttributeDeviceModelName = "device.model.name";
}
