// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class DnsAttributes
{
    /// <summary>
    /// The list of IPv4 or IPv6 addresses resolved during DNS lookup.
    /// </summary>
    public const string AttributeDnsAnswers = "dns.answers";

    /// <summary>
    /// The name being queried.
    /// </summary>
    /// <remarks>
    /// The name represents the queried domain name as it appears in the DNS query without any additional normalization.
    /// </remarks>
    public const string AttributeDnsQuestionName = "dns.question.name";
}
