// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class ExceptionAttributes
{
    /// <summary>
    /// Indicates that the exception is escaping the scope of the span.
    /// </summary>
    [Obsolete("It's no longer recommended to record exceptions that are handled and do not escape the scope of a span.")]
    public const string AttributeExceptionEscaped = "exception.escaped";

    /// <summary>
    /// The exception message.
    /// </summary>
    public const string AttributeExceptionMessage = "exception.message";

    /// <summary>
    /// A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.
    /// </summary>
    public const string AttributeExceptionStacktrace = "exception.stacktrace";

    /// <summary>
    /// The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.
    /// </summary>
    public const string AttributeExceptionType = "exception.type";
}
