// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class GoAttributes
{
    /// <summary>
    /// The type of memory.
    /// </summary>
    public const string AttributeGoMemoryType = "go.memory.type";

    /// <summary>
    /// The type of memory.
    /// </summary>
    public static class GoMemoryTypeValues
    {
        /// <summary>
        /// Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
        /// </summary>
        public const string Stack = "stack";

        /// <summary>
        /// Memory used by the Go runtime, excluding other categories of memory usage described in this enumeration.
        /// </summary>
        public const string Other = "other";
    }
}
