// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class GoAttributes
{
    /// <summary>
    /// The detailed state of the CPU.
    /// </summary>
    /// <remarks>
    /// Value SHOULD match the specific CPU class reported by the Go runtime under <c>/cpu/classes/...</c>. The list of possible values is subject to change with the Go version used.
    /// </remarks>
    public const string AttributeGoCpuDetailedState = "go.cpu.detailed_state";

    /// <summary>
    /// The state of the CPU.
    /// </summary>
    public const string AttributeGoCpuState = "go.cpu.state";

    /// <summary>
    /// The detailed type of memory.
    /// </summary>
    /// <remarks>
    /// Value SHOULD match the specific memory class reported by the Go runtime under <c>/memory/classes/...</c>. The list of possible values is subject to change with the Go version used.
    /// </remarks>
    public const string AttributeGoMemoryDetailedType = "go.memory.detailed_type";

    /// <summary>
    /// The type of memory.
    /// </summary>
    public const string AttributeGoMemoryType = "go.memory.type";

    /// <summary>
    /// The state of the CPU.
    /// </summary>
    public static class GoCpuStateValues
    {
        /// <summary>
        /// CPU time spent running user Go code.
        /// </summary>
        public const string User = "user";

        /// <summary>
        /// CPU time spent performing garbage collection tasks.
        /// </summary>
        public const string Gc = "gc";

        /// <summary>
        /// CPU time spent returning unused memory to the underlying platform.
        /// </summary>
        public const string Scavenge = "scavenge";

        /// <summary>
        /// Available CPU time not spent executing any Go or Go runtime code.
        /// </summary>
        public const string Idle = "idle";
    }

    /// <summary>
    /// The type of memory.
    /// </summary>
    public static class GoMemoryTypeValues
    {
        /// <summary>
        /// Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
        /// </summary>
        public const string Stack = "stack";

        /// <summary>
        /// Memory used by the Go runtime, excluding other categories of memory usage described in this enumeration.
        /// </summary>
        public const string Other = "other";
    }
}
