// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class HerokuAttributes
{
    /// <summary>
    /// Unique identifier for the application.
    /// </summary>
    public const string AttributeHerokuAppId = "heroku.app.id";

    /// <summary>
    /// Commit hash for the current release.
    /// </summary>
    public const string AttributeHerokuReleaseCommit = "heroku.release.commit";

    /// <summary>
    /// Time and date the release was created.
    /// </summary>
    public const string AttributeHerokuReleaseCreationTimestamp = "heroku.release.creation_timestamp";
}
