// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class JsonrpcAttributes
{
    /// <summary>
    /// Protocol version, as specified in the <c>jsonrpc</c> property of the request and its corresponding response.
    /// </summary>
    public const string AttributeJsonrpcProtocolVersion = "jsonrpc.protocol.version";

    /// <summary>
    /// A string representation of the <c>id</c> property of the request and its corresponding response.
    /// </summary>
    /// <remarks>
    /// Under the <a href="https://www.jsonrpc.org/specification">JSON-RPC specification</a>, the <c>id</c> property may be a string, number, null, or omitted entirely. When omitted, the request is treated as a notification. Using <c>null</c> is not equivalent to omitting the <c>id</c>, but it is discouraged.
    /// Instrumentations SHOULD NOT capture this attribute when the <c>id</c> is <c>null</c> or omitted.
    /// </remarks>
    public const string AttributeJsonrpcRequestId = "jsonrpc.request.id";
}
