// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class McpAttributes
{
    /// <summary>
    /// The name of the request or notification method.
    /// </summary>
    public const string AttributeMcpMethodName = "mcp.method.name";

    /// <summary>
    /// The <a href="https://modelcontextprotocol.io/specification/versioning">version</a> of the Model Context Protocol used.
    /// </summary>
    public const string AttributeMcpProtocolVersion = "mcp.protocol.version";

    /// <summary>
    /// The value of the resource uri.
    /// </summary>
    /// <remarks>
    /// This is a URI of the resource provided in the following requests or notifications: <c>resources/read</c>, <c>resources/subscribe</c>, <c>resources/unsubscribe</c>, or <c>notifications/resources/updated</c>.
    /// </remarks>
    public const string AttributeMcpResourceUri = "mcp.resource.uri";

    /// <summary>
    /// Identifies <a href="https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#session-management">MCP session</a>.
    /// </summary>
    public const string AttributeMcpSessionId = "mcp.session.id";

    /// <summary>
    /// The name of the request or notification method.
    /// </summary>
    public static class McpMethodNameValues
    {
        /// <summary>
        /// Notification cancelling a previously-issued request.
        /// </summary>
        public const string NotificationsCancelled = "notifications/cancelled";

        /// <summary>
        /// Request to initialize the MCP client.
        /// </summary>
        public const string Initialize = "initialize";

        /// <summary>
        /// Notification indicating that the MCP client has been initialized.
        /// </summary>
        public const string NotificationsInitialized = "notifications/initialized";

        /// <summary>
        /// Notification indicating the progress for a long-running operation.
        /// </summary>
        public const string NotificationsProgress = "notifications/progress";

        /// <summary>
        /// Request to check that the other party is still alive.
        /// </summary>
        public const string Ping = "ping";

        /// <summary>
        /// Request to list resources available on server.
        /// </summary>
        public const string ResourcesList = "resources/list";

        /// <summary>
        /// Request to list resource templates available on server.
        /// </summary>
        public const string ResourcesTemplatesList = "resources/templates/list";

        /// <summary>
        /// Request to read a resource.
        /// </summary>
        public const string ResourcesRead = "resources/read";

        /// <summary>
        /// Notification indicating that the list of resources has changed.
        /// </summary>
        public const string NotificationsResourcesListChanged = "notifications/resources/list_changed";

        /// <summary>
        /// Request to subscribe to a resource.
        /// </summary>
        public const string ResourcesSubscribe = "resources/subscribe";

        /// <summary>
        /// Request to unsubscribe from resource updates.
        /// </summary>
        public const string ResourcesUnsubscribe = "resources/unsubscribe";

        /// <summary>
        /// Notification indicating that a resource has been updated.
        /// </summary>
        public const string NotificationsResourcesUpdated = "notifications/resources/updated";

        /// <summary>
        /// Request to list prompts available on server.
        /// </summary>
        public const string PromptsList = "prompts/list";

        /// <summary>
        /// Request to get a prompt.
        /// </summary>
        public const string PromptsGet = "prompts/get";

        /// <summary>
        /// Notification indicating that the list of prompts has changed.
        /// </summary>
        public const string NotificationsPromptsListChanged = "notifications/prompts/list_changed";

        /// <summary>
        /// Request to list tools available on server.
        /// </summary>
        public const string ToolsList = "tools/list";

        /// <summary>
        /// Request to call a tool.
        /// </summary>
        public const string ToolsCall = "tools/call";

        /// <summary>
        /// Notification indicating that the list of tools has changed.
        /// </summary>
        public const string NotificationsToolsListChanged = "notifications/tools/list_changed";

        /// <summary>
        /// Request to set the logging level.
        /// </summary>
        public const string LoggingSetLevel = "logging/setLevel";

        /// <summary>
        /// Notification indicating that a message has been received.
        /// </summary>
        public const string NotificationsMessage = "notifications/message";

        /// <summary>
        /// Request to create a sampling message.
        /// </summary>
        public const string SamplingCreateMessage = "sampling/createMessage";

        /// <summary>
        /// Request to complete a prompt.
        /// </summary>
        public const string CompletionComplete = "completion/complete";

        /// <summary>
        /// Request to list roots available on server.
        /// </summary>
        public const string RootsList = "roots/list";

        /// <summary>
        /// Notification indicating that the list of roots has changed.
        /// </summary>
        public const string NotificationsRootsListChanged = "notifications/roots/list_changed";

        /// <summary>
        /// Request from the server to elicit additional information from the user via the client.
        /// </summary>
        public const string ElicitationCreate = "elicitation/create";
    }
}
