// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class MessageAttributes
{
    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [Obsolete("Deprecated, no replacement at this time.")]
    public const string AttributeMessageCompressedSize = "message.compressed_size";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [Obsolete("Deprecated, no replacement at this time.")]
    public const string AttributeMessageId = "message.id";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [Obsolete("Deprecated, no replacement at this time.")]
    public const string AttributeMessageType = "message.type";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [Obsolete("Deprecated, no replacement at this time.")]
    public const string AttributeMessageUncompressedSize = "message.uncompressed_size";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [Obsolete("Deprecated, no replacement at this time.")]
    public static class MessageTypeValues
    {
        /// <summary>
        /// sent.
        /// </summary>
        public const string Sent = "SENT";

        /// <summary>
        /// received.
        /// </summary>
        public const string Received = "RECEIVED";
    }
}
