// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class OpenaiAttributes
{
    /// <summary>
    /// The type of OpenAI API being used.
    /// </summary>
    public const string AttributeOpenaiApiType = "openai.api.type";

    /// <summary>
    /// The service tier requested. May be a specific tier, default, or auto.
    /// </summary>
    public const string AttributeOpenaiRequestServiceTier = "openai.request.service_tier";

    /// <summary>
    /// The service tier used for the response.
    /// </summary>
    public const string AttributeOpenaiResponseServiceTier = "openai.response.service_tier";

    /// <summary>
    /// A fingerprint to track any eventual change in the Generative AI environment.
    /// </summary>
    public const string AttributeOpenaiResponseSystemFingerprint = "openai.response.system_fingerprint";

    /// <summary>
    /// The type of OpenAI API being used.
    /// </summary>
    public static class OpenaiApiTypeValues
    {
        /// <summary>
        /// The OpenAI <a href="https://developers.openai.com/api/reference/chat-completions/overview">Chat Completions API</a>.
        /// </summary>
        public const string ChatCompletions = "chat_completions";

        /// <summary>
        /// The OpenAI <a href="https://developers.openai.com/api/reference/responses/overview">Responses API</a>.
        /// </summary>
        public const string Responses = "responses";
    }

    /// <summary>
    /// The service tier requested. May be a specific tier, default, or auto.
    /// </summary>
    public static class OpenaiRequestServiceTierValues
    {
        /// <summary>
        /// The system will utilize scale tier credits until they are exhausted.
        /// </summary>
        public const string Auto = "auto";

        /// <summary>
        /// The system will utilize the default scale tier.
        /// </summary>
        public const string Default = "default";
    }
}
