// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class OracleAttributes
{
    /// <summary>
    /// The database domain associated with the connection.
    /// </summary>
    /// <remarks>
    /// This attribute SHOULD be set to the value of the <c>DB_DOMAIN</c> initialization parameter,
    /// as exposed in <c>v$parameter</c>. <c>DB_DOMAIN</c> defines the domain portion of the global
    /// database name and SHOULD be configured when a database is, or may become, part of a
    /// distributed environment. Its value consists of one or more valid identifiers
    /// (alphanumeric ASCII characters) separated by periods.
    /// </remarks>
    public const string AttributeOracleDbDomain = "oracle.db.domain";

    /// <summary>
    /// The instance name associated with the connection in an Oracle Real Application Clusters environment.
    /// </summary>
    /// <remarks>
    /// There can be multiple instances associated with a single database service. It indicates the
    /// unique instance name to which the connection is currently bound. For non-RAC databases, this value
    /// defaults to the <c>oracle.db.name</c>.
    /// </remarks>
    public const string AttributeOracleDbInstanceName = "oracle.db.instance.name";

    /// <summary>
    /// The database name associated with the connection.
    /// </summary>
    /// <remarks>
    /// This attribute SHOULD be set to the value of the parameter <c>DB_NAME</c> exposed in <c>v$parameter</c>.
    /// </remarks>
    public const string AttributeOracleDbName = "oracle.db.name";

    /// <summary>
    /// The pluggable database (PDB) name associated with the connection.
    /// </summary>
    /// <remarks>
    /// This attribute SHOULD reflect the PDB that the session is currently connected to.
    /// If instrumentation cannot reliably obtain the active PDB name for each operation
    /// without issuing an additional query (such as <c>SELECT SYS_CONTEXT</c>), it is
    /// RECOMMENDED to fall back to the PDB name specified at connection establishment.
    /// </remarks>
    public const string AttributeOracleDbPdb = "oracle.db.pdb";

    /// <summary>
    /// The service name currently associated with the database connection.
    /// </summary>
    /// <remarks>
    /// The effective service name for a connection can change during its lifetime,
    /// for example after executing sql, <c>ALTER SESSION</c>. If an instrumentation cannot reliably
    /// obtain the current service name for each operation without issuing an additional
    /// query (such as <c>SELECT SYS_CONTEXT</c>), it is RECOMMENDED to fall back to the
    /// service name originally provided at connection establishment.
    /// </remarks>
    public const string AttributeOracleDbService = "oracle.db.service";
}
