// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class OracleCloudAttributes
{
    /// <summary>
    /// The OCI realm identifier that indicates the isolated partition in which the tenancy and its resources reside.
    /// </summary>
    /// <remarks>
    /// See <a href="https://docs.oracle.com/iaas/Content/General/Concepts/regions.htm">OCI documentation on realms</a>.
    /// </remarks>
    public const string AttributeOracleCloudRealm = "oracle_cloud.realm";
}
