// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class SecurityRuleAttributes
{
    /// <summary>
    /// A categorization value keyword used by the entity using the rule for detection of this event.
    /// </summary>
    public const string AttributeSecurityRuleCategory = "security_rule.category";

    /// <summary>
    /// The description of the rule generating the event.
    /// </summary>
    public const string AttributeSecurityRuleDescription = "security_rule.description";

    /// <summary>
    /// Name of the license under which the rule used to generate this event is made available.
    /// </summary>
    public const string AttributeSecurityRuleLicense = "security_rule.license";

    /// <summary>
    /// The name of the rule or signature generating the event.
    /// </summary>
    public const string AttributeSecurityRuleName = "security_rule.name";

    /// <summary>
    /// Reference URL to additional information about the rule used to generate this event.
    /// </summary>
    /// <remarks>
    /// The URL can point to the vendor’s documentation about the rule. If that’s not available, it can also be a link to a more general page describing this type of alert.
    /// </remarks>
    public const string AttributeSecurityRuleReference = "security_rule.reference";

    /// <summary>
    /// Name of the ruleset, policy, group, or parent category in which the rule used to generate this event is a member.
    /// </summary>
    public const string AttributeSecurityRuleRulesetName = "security_rule.ruleset.name";

    /// <summary>
    /// A rule ID that is unique within the scope of a set or group of agents, observers, or other entities using the rule for detection of this event.
    /// </summary>
    public const string AttributeSecurityRuleUuid = "security_rule.uuid";

    /// <summary>
    /// The version / revision of the rule being used for analysis.
    /// </summary>
    public const string AttributeSecurityRuleVersion = "security_rule.version";
}
