// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class ThreadAttributes
{
    /// <summary>
    /// Current "managed" thread ID (as opposed to OS thread ID)
    /// </summary>
    public const string AttributeThreadId = "thread.id";

    /// <summary>
    /// Current thread name
    /// </summary>
    public const string AttributeThreadName = "thread.name";
}
