namespace OpenTelemetry.Instrumentation.EntityFrameworkCore;

internal class EntityFrameworkConstants
{
    public const string OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_TEXT = "OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_TEXT";
    public const string OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_STORED_PROCEDURE = "OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_STORED_PROCEDURE";
}
