// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file is auto-generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SchemaVersion.cs.j2'. Do not edit.</auto-generated>

#nullable enable

namespace OpenTelemetry.SemanticConventions.Incubating;

/// <summary>
/// Constants for OpenTelemetry semantic convention schema versions.
/// </summary>
public static class SchemaVersion
{
    /// <summary>
    /// The OpenTelemetry semantic convention version for this package.
    /// </summary>
    public const string Value = "1.41.0";
}
