// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file is auto-generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2'. Do not edit.</auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class HttpAttributes
{
    /// <summary>
    /// HTTP request headers, <c><key></c> being the normalized HTTP Header name (lowercase), the value being the header values.
    /// </summary>
    /// <remarks>
    /// Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
    /// Including all request headers can be a security risk - explicit configuration helps avoid leaking sensitive information.
    /// <p>
    /// The <c>User-Agent</c> header is already captured in the <c>user_agent.original</c> attribute.
    /// Users MAY explicitly configure instrumentations to capture them even though it is not recommended.
    /// <p>
    /// The attribute value MUST consist of either multiple header values as an array of strings
    /// or a single-item array containing a possibly comma-concatenated string, depending on the way
    /// the HTTP library provides access to headers.
    /// <p>
    /// Examples:
    /// <ul>
    ///   <li>A header <c>Content-Type: application/json</c> SHOULD be recorded as the <c>http.request.header.content-type</c>
    /// attribute with value <c>["application/json"]</c>.</li>
    ///   <li>A header <c>X-Forwarded-For: 1.2.3.4, 1.2.3.5</c> SHOULD be recorded as the <c>http.request.header.x-forwarded-for</c>
    /// attribute with value <c>["1.2.3.4", "1.2.3.5"]</c> or <c>["1.2.3.4, 1.2.3.5"]</c> depending on the HTTP library.</li>
    /// </ul>
    /// </remarks>
    public const string AttributeHttpRequestHeaderTemplate = "http.request.header";

    /// <summary>
    /// HTTP request method.
    /// </summary>
    /// <remarks>
    /// HTTP request method value SHOULD be "known" to the instrumentation.
    /// By default, this convention defines "known" methods as the ones listed in <a href="https://www.rfc-editor.org/rfc/rfc9110.html#name-methods">RFC9110</a>,
    /// the PATCH method defined in <a href="https://www.rfc-editor.org/rfc/rfc5789.html">RFC5789</a>
    /// and the QUERY method defined in <a href="https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/?include_text=1">httpbis-safe-method-w-body</a>.
    /// <p>
    /// If the HTTP request method is not known to instrumentation, it MUST set the <c>http.request.method</c> attribute to <c>_OTHER</c>.
    /// <p>
    /// If the HTTP instrumentation could end up converting valid HTTP request methods to <c>_OTHER</c>, then it MUST provide a way to override
    /// the list of known HTTP methods. If this override is done via environment variable, then the environment variable MUST be named
    /// OTEL_INSTRUMENTATION_HTTP_KNOWN_METHODS and support a comma-separated list of case-sensitive known HTTP methods.
    /// <p>
    ///
    /// If this override is done via declarative configuration, then the list MUST be configurable via the <c>known_methods</c> property
    /// (an array of case-sensitive strings with minimum items 0) under <c>.instrumentation/development.general.http.client</c> and/or
    /// <c>.instrumentation/development.general.http.server</c>.
    /// <p>
    /// In either case, this list MUST be a full override of the default known methods,
    /// it is not a list of known methods in addition to the defaults.
    /// <p>
    /// HTTP method names are case-sensitive and <c>http.request.method</c> attribute value MUST match a known HTTP method name exactly.
    /// Instrumentations for specific web frameworks that consider HTTP methods to be case insensitive, SHOULD populate a canonical equivalent.
    /// Tracing instrumentations that do so, MUST also set <c>http.request.method_original</c> to the original value.
    /// </remarks>
    public const string AttributeHttpRequestMethod = "http.request.method";

    /// <summary>
    /// Original HTTP method sent by the client in the request line.
    /// </summary>
    public const string AttributeHttpRequestMethodOriginal = "http.request.method_original";

    /// <summary>
    /// The ordinal number of request resending attempt (for any reason, including redirects).
    /// </summary>
    /// <remarks>
    /// The resend count SHOULD be updated each time an HTTP request gets resent by the client, regardless of what was the cause of the resending (e.g. redirection, authorization failure, 503 Server Unavailable, network issues, or any other).
    /// </remarks>
    public const string AttributeHttpRequestResendCount = "http.request.resend_count";

    /// <summary>
    /// HTTP response headers, <c><key></c> being the normalized HTTP Header name (lowercase), the value being the header values.
    /// </summary>
    /// <remarks>
    /// Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
    /// Including all response headers can be a security risk - explicit configuration helps avoid leaking sensitive information.
    /// <p>
    /// Users MAY explicitly configure instrumentations to capture them even though it is not recommended.
    /// <p>
    /// The attribute value MUST consist of either multiple header values as an array of strings
    /// or a single-item array containing a possibly comma-concatenated string, depending on the way
    /// the HTTP library provides access to headers.
    /// <p>
    /// Examples:
    /// <ul>
    ///   <li>A header <c>Content-Type: application/json</c> header SHOULD be recorded as the <c>http.request.response.content-type</c>
    /// attribute with value <c>["application/json"]</c>.</li>
    ///   <li>A header <c>My-custom-header: abc, def</c> header SHOULD be recorded as the <c>http.response.header.my-custom-header</c>
    /// attribute with value <c>["abc", "def"]</c> or <c>["abc, def"]</c> depending on the HTTP library.</li>
    /// </ul>
    /// </remarks>
    public const string AttributeHttpResponseHeaderTemplate = "http.response.header";

    /// <summary>
    /// <a href="https://tools.ietf.org/html/rfc7231#section-6">HTTP response status code</a>.
    /// </summary>
    public const string AttributeHttpResponseStatusCode = "http.response.status_code";

    /// <summary>
    /// The matched route template for the request. This MUST be low-cardinality and include all static path segments, with dynamic path segments represented with placeholders.
    /// </summary>
    /// <remarks>
    /// MUST NOT be populated when this is not supported by the HTTP server framework as the route attribute should have low-cardinality and the URI path can NOT substitute it.
    /// SHOULD include the <a href="/docs/http/http-spans.md#http-server-definitions">application root</a> if there is one.
    /// <p>
    /// A static path segment is a part of the route template with a fixed, low-cardinality value. This includes literal strings like <c>/users/</c> and placeholders that
    /// are constrained to a finite, predefined set of values, e.g. <c>{controller}</c> or <c>{action}</c>.
    /// <p>
    /// A dynamic path segment is a placeholder for a value that can have high cardinality and is not constrained to a predefined list like static path segments.
    /// <p>
    /// Instrumentations SHOULD use routing information provided by the corresponding web framework. They SHOULD pick the most precise source of routing information and MAY
    /// support custom route formatting. Instrumentations SHOULD document the format and the API used to obtain the route string.
    /// </remarks>
    public const string AttributeHttpRoute = "http.route";

    /// <summary>
    /// HTTP request method.
    /// </summary>
    public static class HttpRequestMethodValues
    {
        /// <summary>
        /// CONNECT method.
        /// </summary>
        public const string Connect = "CONNECT";

        /// <summary>
        /// DELETE method.
        /// </summary>
        public const string Delete = "DELETE";

        /// <summary>
        /// GET method.
        /// </summary>
        public const string Get = "GET";

        /// <summary>
        /// HEAD method.
        /// </summary>
        public const string Head = "HEAD";

        /// <summary>
        /// OPTIONS method.
        /// </summary>
        public const string Options = "OPTIONS";

        /// <summary>
        /// PATCH method.
        /// </summary>
        public const string Patch = "PATCH";

        /// <summary>
        /// POST method.
        /// </summary>
        public const string Post = "POST";

        /// <summary>
        /// PUT method.
        /// </summary>
        public const string Put = "PUT";

        /// <summary>
        /// TRACE method.
        /// </summary>
        public const string Trace = "TRACE";

        /// <summary>
        /// QUERY method.
        /// </summary>
        public const string Query = "QUERY";

        /// <summary>
        /// Any HTTP method that the instrumentation has no prior knowledge of.
        /// </summary>
        public const string Other = "_OTHER";
    }
}
