name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please make sure to fill out the entire form below, providing as much context as you can in order to help us triage and track down your request as quickly as possible.

        Before opening a feature request, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry/). If so, please [open an issue on opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature request concern?
      multiple: false
      options:
        - OpenTelemetry.Exporter.Geneva
        - OpenTelemetry.Exporter.InfluxDB
        - OpenTelemetry.Exporter.Instana
        - OpenTelemetry.Exporter.OneCollector
        - OpenTelemetry.Exporter.Stackdriver
        - OpenTelemetry.Extensions
        - OpenTelemetry.Extensions.AWS
        - OpenTelemetry.Extensions.Enrichment
        - OpenTelemetry.Instrumentation.AspNet
        - OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule
        - OpenTelemetry.Instrumentation.AspNetCore
        - OpenTelemetry.Instrumentation.AWS
        - OpenTelemetry.Instrumentation.AWSLambda
        - OpenTelemetry.Instrumentation.Cassandra
        - OpenTelemetry.Instrumentation.ElasticsearchClient
        - OpenTelemetry.Instrumentation.EntityFrameworkCore
        - OpenTelemetry.Instrumentation.EventCounters
        - OpenTelemetry.Instrumentation.GrpcCore
        - OpenTelemetry.Instrumentation.GrpcNetClient
        - OpenTelemetry.Instrumentation.Hangfire
        - OpenTelemetry.Instrumentation.Http
        - OpenTelemetry.Instrumentation.MassTransit
        - OpenTelemetry.Instrumentation.MySqlData
        - OpenTelemetry.Instrumentation.Owin
        - OpenTelemetry.Instrumentation.Process
        - OpenTelemetry.Instrumentation.Quartz
        - OpenTelemetry.Instrumentation.Runtime
        - OpenTelemetry.Instrumentation.SqlClient
        - OpenTelemetry.Instrumentation.StackExchangeRedis
        - OpenTelemetry.Instrumentation.Wcf
        - OpenTelemetry.PersistentStorage.Abstractions
        - OpenTelemetry.PersistentStorage.FileSystem
        - OpenTelemetry.ResourceDetectors.AWS
        - OpenTelemetry.ResourceDetectors.Azure
        - OpenTelemetry.ResourceDetectors.Container
        - OpenTelemetry.ResourceDetectors.Host
        - OpenTelemetry.ResourceDetectors.Process
        - OpenTelemetry.ResourceDetectors.ProcessRuntime
        - OpenTelemetry.Sampler.AWS
        - OpenTelemetry.SemanticConventions
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: If so, provide a concise description of the problem.

  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: Describe the solution you would like.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Which alternative solutions or features have you considered?
      description: Describe alternatives you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this feature request.
