name: Release request
title: "[release request] "
description: Request a release for a component
labels: ["release"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out this form to request a release of one of the components in this repository.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this release request concern?
      multiple: false
      options:
        - OpenTelemetry.Exporter.Geneva
        - OpenTelemetry.Exporter.InfluxDB
        - OpenTelemetry.Exporter.Instana
        - OpenTelemetry.Exporter.OneCollector
        - OpenTelemetry.Exporter.Stackdriver
        - OpenTelemetry.Extensions
        - OpenTelemetry.Extensions.AWS
        - OpenTelemetry.Extensions.Enrichment
        - OpenTelemetry.Instrumentation.AspNet
        - OpenTelemetry.Instrumentation.AspNet.TelemetryHttpModule
        - OpenTelemetry.Instrumentation.AspNetCore
        - OpenTelemetry.Instrumentation.AWS
        - OpenTelemetry.Instrumentation.AWSLambda
        - OpenTelemetry.Instrumentation.Cassandra
        - OpenTelemetry.Instrumentation.ConfluentKafka
        - OpenTelemetry.Instrumentation.ElasticsearchClient
        - OpenTelemetry.Instrumentation.EntityFrameworkCore
        - OpenTelemetry.Instrumentation.EventCounters
        - OpenTelemetry.Instrumentation.GrpcCore
        - OpenTelemetry.Instrumentation.GrpcNetClient
        - OpenTelemetry.Instrumentation.Hangfire
        - OpenTelemetry.Instrumentation.Http
        - OpenTelemetry.Instrumentation.MassTransit
        - OpenTelemetry.Instrumentation.MySqlData
        - OpenTelemetry.Instrumentation.Owin
        - OpenTelemetry.Instrumentation.Process
        - OpenTelemetry.Instrumentation.Quartz
        - OpenTelemetry.Instrumentation.Runtime
        - OpenTelemetry.Instrumentation.ServiceFabricRemoting       
        - OpenTelemetry.Instrumentation.SqlClient
        - OpenTelemetry.Instrumentation.StackExchangeRedis
        - OpenTelemetry.Instrumentation.Wcf
        - OpenTelemetry.PersistentStorage.Abstractions
        - OpenTelemetry.PersistentStorage.FileSystem
        - OpenTelemetry.Resources.AWS
        - OpenTelemetry.Resources.Azure
        - OpenTelemetry.Resources.Container
        - OpenTelemetry.Resources.Gcp
        - OpenTelemetry.Resources.Host
        - OpenTelemetry.Resources.OperatingSystem
        - OpenTelemetry.Resources.Process
        - OpenTelemetry.Resources.ProcessRuntime
        - OpenTelemetry.Sampler.AWS
        - OpenTelemetry.SemanticConventions
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: |
        What is the requested version for the release?
        Version must specify [Major].[Minor].[Patch] and may also include prerelease information -[alpha|beta|rc].[Increment].
        Examples:
        * 1.9.0
        * 1.10.0-rc.1
        * 1.12.0-beta.2
        * 0.2.0-alpha.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this release request.
