// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file is auto-generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2'. Do not edit.</auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions.Incubating;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class CodeAttributes
{
    /// <summary>
    /// Deprecated, use <c>code.column.number</c>.
    /// </summary>
    [Obsolete("Replaced by <c>code.column.number</c>.")]
    public const string AttributeCodeColumn = "code.column";

    /// <summary>
    /// Deprecated, use <c>code.file.path</c> instead.
    /// </summary>
    [Obsolete("Replaced by <c>code.file.path</c>.")]
    public const string AttributeCodeFilepath = "code.filepath";

    /// <summary>
    /// Deprecated, use <c>code.function.name</c> instead.
    /// </summary>
    [Obsolete("Value should be included in <c>code.function.name</c> which is expected to be a fully-qualified name.")]
    public const string AttributeCodeFunction = "code.function";

    /// <summary>
    /// Deprecated, use <c>code.line.number</c> instead.
    /// </summary>
    [Obsolete("Replaced by <c>code.line.number</c>.")]
    public const string AttributeCodeLineno = "code.lineno";

    /// <summary>
    /// Deprecated, namespace is now included into <c>code.function.name</c>.
    /// </summary>
    [Obsolete("Value should be included in <c>code.function.name</c> which is expected to be a fully-qualified name.")]
    public const string AttributeCodeNamespace = "code.namespace";
}
