{
 "title": "process instrumentation",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "virtual memory usage",
   "type": "timeseries",
   "description": "The amount of committed virtual memory for this process. One way to think of this is all the address space this process can read from without trigerring an access violation; this includes memory backed solely by RAM, by a swapfile/pagefile and by other mapped files on disk.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_memory_virtual_By", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "physical memory usage",
   "type": "timeseries",
   "description": "The amount of physical memory allocated for this process.",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 0 },
   "targets": [
    { "expr": "process_memory_usage_By", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu time",
   "type": "timeseries",
   "description": "Total CPU seconds broken down by states.\nProcess.UserProcessorTime: Gets the user processor time for this process.\n\nProcess.PrivilegedProcessorTime: Gets the privileged processor time for this process.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "process_cpu_time_s", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "timeseries",
   "description": "Difference in process.cpu.time since the last measurement, divided by the elapsed time and number of CPUs available to the process.",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "100 * (delta(process_cpu_time_s{state='system'}[30s])/ignoring(state)(process_cpu_count__processors_* 30))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * (delta(process_cpu_time_s{state='user'}[30s])/ignoring(state)(process_cpu_count__processors_* 30))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "thread count",
   "type": "timeseries",
   "description": "Process threads count.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "targets": [
    { "expr": "process_threads__threads_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu count",
   "type": "gauge",
   "description": "The number of processors (CPU cores) available to the current process.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_count__processors_", "legendFormat": "__auto" }
   ]
  }
 ]
}