// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using OpenTelemetry.SemanticConventions.SourceGeneration;
using System;
using System.Collections.Generic;
using System.Text;
using OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the source file completing a partial class marked with
/// <c>[SemanticConventionAttributes("&lt;prefix&gt;")]</c>.
///
/// Member shape (constant naming, enum-value classes, XML doc comment layout) is
/// byte-identical to contrib's <c>OpenTelemetry.SemanticConventions.SourceGeneration</c>
/// output for the matching semconv version. The outer class declaration is a
/// partial because the marker pattern attaches generated members to a user-authored
/// class; contrib emits its own class declaration. Byte-identity is checked on the
/// member region.
/// </summary>
internal static class AttributesEmitter
{
    public static FileWithName Generate(MarkerModel marker, RegistryModel registry)
    {
        var group = FindGroupForPrefix(registry, marker.Prefix);
        var attributes = ResolveAttributes(registry, marker.Prefix, marker.Filter, group);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, attributes, marker.Filter);

        var fileName = GeneratedSourceNames.ForPartialType(marker.ContainingNamespace, marker.ClassName);
        return new FileWithName(fileName, builder.ToString());
    }

    private static GroupModel? FindGroupForPrefix(RegistryModel registry, string prefix)
    {
        foreach (var group in registry.Groups)
        {
            if (string.Equals(group.Prefix, prefix, StringComparison.Ordinal))
                return group;
        }
        return null;
    }

    private static List<AttributeModel> ResolveAttributes(
        RegistryModel registry,
        string prefix,
        StabilityFilter filter,
        GroupModel? group)
    {
        if (group is { } g && !g.AttributeRefs.IsEmpty)
        {
            var byKey = new Dictionary<string, AttributeModel>(StringComparer.Ordinal);
            foreach (var attr in registry.Catalog)
                byKey[attr.Key] = attr;

            var resolved = new List<AttributeModel>();
            foreach (var key in g.AttributeRefs)
            {
                if (byKey.TryGetValue(key, out var match) &&
                    StabilityFiltering.IsIncludedOrDeprecated(match.Stability, match.Deprecated, filter))
                {
                    resolved.Add(match);
                }
            }
            return resolved;
        }

        var fallback = new List<AttributeModel>();
        var dotted = prefix + ".";
        foreach (var attr in registry.Catalog)
        {
            if (string.Equals(attr.Key, prefix, StringComparison.Ordinal) ||
                attr.Key.StartsWith(dotted, StringComparison.Ordinal))
            {
                if (!StabilityFiltering.IsIncludedOrDeprecated(attr.Stability, attr.Deprecated, filter))
                    continue;

                fallback.Add(attr);
            }
        }
        fallback.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.Key, b.Key));
        return fallback;
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(
        StringBuilder builder,
        string className,
        List<AttributeModel> attributes,
        StabilityFilter filter)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var attr in attributes)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteAttributeConstant(builder, attr);
        }

        foreach (var attr in attributes)
        {
            if (attr.Type is not AttributeTypeModel.EnumType enumType) continue;
            builder.AppendLine();
            WriteEnumValueClass(builder, attr, enumType, filter);
        }

        builder.AppendLine("}");
    }

    private static void WriteAttributeConstant(StringBuilder builder, AttributeModel attr)
    {
        WriteSummaryComment(builder, attr.Brief, indent: 4);
        if (!string.IsNullOrEmpty(attr.Note))
            WriteRemarksComment(builder, attr.Note, indent: 4);
        WriteExamplesComment(builder, attr.Examples, indent: 4);
        WriteObsolete(builder, attr.Deprecated, indent: 4);

        var memberName = AttributeMemberName(attr.Key, attr.Type);
        builder.Append("    public const string ").Append(memberName)
               .Append(" = \"").Append(attr.Key).AppendLine("\";");
    }

    private static void WriteEnumValueClass(
        StringBuilder builder,
        AttributeModel attr,
        AttributeTypeModel.EnumType enumType,
        StabilityFilter filter)
    {
        WriteSummaryComment(builder, attr.Brief, indent: 4);
        WriteObsolete(builder, attr.Deprecated, indent: 4);

        var enumClassName = ToPascalCase(attr.Key) + "Values";
        builder.Append("    public static class ").AppendLine(enumClassName);
        builder.AppendLine("    {");

        var first = true;
        foreach (var member in enumType.Members)
        {
            if (!StabilityFiltering.IsIncludedOrDeprecated(member.Stability, member.Deprecated ?? attr.Deprecated, filter))
                continue;

            if (!first) builder.AppendLine();
            first = false;
            WriteEnumMember(builder, member);
        }

        builder.AppendLine("    }");
    }

    private static void WriteEnumMember(StringBuilder builder, EnumMemberModel member)
    {
        var brief = string.IsNullOrEmpty(member.Brief) ? member.Id + "." : member.Brief;
        WriteSummaryComment(builder, brief, indent: 8);
        WriteObsolete(builder, member.Deprecated, indent: 8);

        var memberName = ToPascalCase(member.Id);
        builder.Append("        public const string ").Append(memberName)
               .Append(" = \"").Append(member.Value).AppendLine("\";");
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        var lines = SplitLines(text);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in lines)
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    private static void WriteRemarksComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        var lines = SplitLines(text);
        builder.Append(pad).AppendLine("/// <remarks>");
        foreach (var line in lines)
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    private static void WriteExamplesComment(StringBuilder builder, EquatableArray<string> examples, int indent)
    {
        if (examples.Length == 0)
            return;

        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <remarks>");
        builder.Append(pad).AppendLine("/// Examples:");
        foreach (var example in examples)
        {
            AppendDocLine(builder, pad, "- " + example);
        }
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    private static void AppendDocLine(StringBuilder builder, string pad, string line)
    {
        builder.Append(pad).Append("///");
        if (!string.IsNullOrEmpty(line))
            builder.Append(' ').Append(line);
        builder.AppendLine();
    }

    private static void WriteObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        if (deprecated is null) return;

        var pad = new string(' ', indent);
        var message = deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    internal static string AttributeMemberName(string key, AttributeTypeModel type)
    {
        var pascal = ToPascalCase(key);
        return type is AttributeTypeModel.Template
            ? "Attribute" + pascal + "Template"
            : "Attribute" + pascal;
    }

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;

        foreach (var line in text.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');
            yield return trimmed;
        }
    }

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
