// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using OpenTelemetry.SemanticConventions.SourceGeneration;
using System;
using System.Collections.Generic;
using System.Text;
using OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits typed <c>System.Diagnostics.Metrics.Meter</c> factory wrappers for
/// every metric in the resolved registry whose <c>prefix</c> matches the marker
/// argument. Each wrapper is an extension method on <c>Meter</c> that returns
/// a strongly-typed instrument with the registry's name, unit, and description
/// embedded.
///
/// Per-metric stability is propagated to the extension method only for
/// <c>stability: deprecated</c>, which projects to <c>[Obsolete]</c>. This
/// matches contrib, Java, and Python upstream generators, which carry no
/// per-symbol annotation for non-stable tiers — stable/incubating separation
/// is handled at the Weaver-template/registry-filter layer, not the symbol
/// layer.
///
/// Audit (pinned-goal directive, Phase B-2): this emitter writes extension
/// methods on a consumer-provided <c>Meter</c> (<c>this Meter meter</c>) only.
/// No generated global <c>Meter</c> singletons, no
/// <c>private static readonly Meter ... = new Meter(...)</c>. Consumers own
/// runtime <c>Meter</c> instances and pick their own name/version/scope; the
/// generator only emits typed factory wrappers over the BCL surface.
/// </summary>
internal static class MetersEmitter
{
    public static FileWithName Generate(MetersMarkerModel marker, InstrumentRegistryModel registry)
    {
        var meters = FilterByPrefix(registry, marker.Prefix, marker.Filter);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, meters);

        return new FileWithName($"{marker.ClassName}.g.cs", builder.ToString());
    }

    private static List<MetricDescriptorModel> FilterByPrefix(InstrumentRegistryModel registry, string prefix, StabilityFilter filter)
    {
        var result = new List<MetricDescriptorModel>();
        foreach (var meter in registry.Metrics)
        {
            if (!PrefixMatches(meter.MetricName, prefix))
                continue;

            // Stability gate. Deprecated rows survive every projection until
            // upstream drops them (contrib/Java/Python parity): the
            // [Obsolete] symbol stays so consumers can migrate at their pace.
            if (!StabilityFiltering.IsIncludedOrDeprecated(meter.Stability, meter.Deprecated, filter))
                continue;

            result.Add(meter);
        }
        result.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.MetricName, b.MetricName));
        return result;
    }

    private static bool PrefixMatches(string metricName, string prefix)
    {
        if (string.Equals(metricName, prefix, StringComparison.Ordinal)) return true;
        if (metricName.Length <= prefix.Length) return false;
        if (!metricName.StartsWith(prefix, StringComparison.Ordinal)) return false;
        return metricName[prefix.Length] == '.';
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(StringBuilder builder, string className, List<MetricDescriptorModel> meters)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Typed factory extensions for OpenTelemetry semantic-convention metric instruments.");
        builder.AppendLine("/// Each method creates an instrument with the registry-defined name, unit, and description.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var meter in meters)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteFactory(builder, meter);
        }

        builder.AppendLine("}");
    }

    private static void WriteFactory(StringBuilder builder, MetricDescriptorModel meter)
    {
        WriteSummaryComment(builder, meter.Brief, indent: 4);
        if (!string.IsNullOrEmpty(meter.Note))
            WriteRemarksComment(builder, meter.Note, indent: 4);
        WriteStabilityAttribute(builder, meter, indent: 4);

        var methodName = "Create" + ToPascalCase(meter.MetricName) + ToPascalCase(meter.Instrument);
        var valueType = MeterValueTypeRules.SelectValueType(meter.Instrument, meter.Unit);
        var instrumentType = ResolveInstrumentType(meter.Instrument, valueType);

        switch (meter.Instrument)
        {
            case "gauge":
            case "observablegauge":
                builder.Append("    public static global::System.Diagnostics.Metrics.").Append(instrumentType)
                       .Append(' ').Append(methodName).AppendLine("(");
                builder.AppendLine("        this global::System.Diagnostics.Metrics.Meter meter,");
                builder.Append("        global::System.Func<").Append(valueType).AppendLine("> observeValue)");
                builder.Append("        => meter.CreateObservableGauge<").Append(valueType).AppendLine(">(");
                builder.Append("            name: \"").Append(meter.MetricName).AppendLine("\",");
                builder.AppendLine("            observeValue: observeValue,");
                builder.Append("            unit: \"").Append(EscapeForString(meter.Unit)).AppendLine("\",");
                builder.Append("            description: \"").Append(EscapeForString(meter.Brief)).AppendLine("\");");
                break;

            case "observablecounter":
                builder.Append("    public static global::System.Diagnostics.Metrics.").Append(instrumentType)
                       .Append(' ').Append(methodName).AppendLine("(");
                builder.AppendLine("        this global::System.Diagnostics.Metrics.Meter meter,");
                builder.Append("        global::System.Func<").Append(valueType).AppendLine("> observeValue)");
                builder.Append("        => meter.CreateObservableCounter<").Append(valueType).AppendLine(">(");
                builder.Append("            name: \"").Append(meter.MetricName).AppendLine("\",");
                builder.AppendLine("            observeValue: observeValue,");
                builder.Append("            unit: \"").Append(EscapeForString(meter.Unit)).AppendLine("\",");
                builder.Append("            description: \"").Append(EscapeForString(meter.Brief)).AppendLine("\");");
                break;

            case "observableupdowncounter":
                builder.Append("    public static global::System.Diagnostics.Metrics.").Append(instrumentType)
                       .Append(' ').Append(methodName).AppendLine("(");
                builder.AppendLine("        this global::System.Diagnostics.Metrics.Meter meter,");
                builder.Append("        global::System.Func<").Append(valueType).AppendLine("> observeValue)");
                builder.Append("        => meter.CreateObservableUpDownCounter<").Append(valueType).AppendLine(">(");
                builder.Append("            name: \"").Append(meter.MetricName).AppendLine("\",");
                builder.AppendLine("            observeValue: observeValue,");
                builder.Append("            unit: \"").Append(EscapeForString(meter.Unit)).AppendLine("\",");
                builder.Append("            description: \"").Append(EscapeForString(meter.Brief)).AppendLine("\");");
                break;

            default:
                builder.Append("    public static global::System.Diagnostics.Metrics.").Append(instrumentType)
                       .Append(' ').Append(methodName).AppendLine("(");
                builder.AppendLine("        this global::System.Diagnostics.Metrics.Meter meter)");
                builder.Append("        => meter.").Append(InstrumentFactoryMethod(meter.Instrument))
                       .Append('<').Append(valueType).AppendLine(">(");
                builder.Append("            name: \"").Append(meter.MetricName).AppendLine("\",");
                builder.Append("            unit: \"").Append(EscapeForString(meter.Unit)).AppendLine("\",");
                builder.Append("            description: \"").Append(EscapeForString(meter.Brief)).AppendLine("\");");
                break;
        }
    }

    private static string ResolveInstrumentType(string instrument, string valueType) => instrument switch
    {
        "histogram" => $"Histogram<{valueType}>",
        "counter" => $"Counter<{valueType}>",
        "updowncounter" => $"UpDownCounter<{valueType}>",
        "gauge" => $"ObservableGauge<{valueType}>",
        "observablegauge" => $"ObservableGauge<{valueType}>",
        "observablecounter" => $"ObservableCounter<{valueType}>",
        "observableupdowncounter" => $"ObservableUpDownCounter<{valueType}>",
        _ => $"Instrument<{valueType}>"
    };

    private static string InstrumentFactoryMethod(string instrument) => instrument switch
    {
        "histogram" => "CreateHistogram",
        "counter" => "CreateCounter",
        "updowncounter" => "CreateUpDownCounter",
        _ => "CreateHistogram"
    };

    private static void WriteStabilityAttribute(StringBuilder builder, MetricDescriptorModel meter, int indent)
    {
        if (meter.Stability != StabilityModel.Deprecated && meter.Deprecated is null) return;

        var pad = new string(' ', indent);
        var message = meter.Deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            null => "Deprecated.",
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    private static void WriteRemarksComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <remarks>");
        foreach (var line in SplitLines(text))
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    private static void AppendDocLine(StringBuilder builder, string pad, string line)
    {
        builder.Append(pad).Append("///");
        if (!string.IsNullOrEmpty(line))
            builder.Append(' ').Append(line);
        builder.AppendLine();
    }

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;
        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }
            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;
        foreach (var line in text.Split('\n'))
            yield return line.TrimEnd('\r');
    }

    private static string EscapeForString(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
