// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using OpenTelemetry.SemanticConventions.SourceGeneration;
using System;
using System.Collections.Generic;
using System.Text;
using OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the source file completing a partial class marked with
/// <c>[SemanticConventionMetrics("&lt;prefix&gt;")]</c>.
///
/// For each metric group whose <c>metric_name</c> starts with the requested prefix the emitter
/// produces:
/// <list type="bullet">
///   <item><description>A <c>public const string Metric&lt;PascalName&gt; = "&lt;metric.name&gt;";</c> constant.</description></item>
///   <item><description>A <c>public static partial class &lt;PascalName&gt;Descriptor</c> carrying
///         <c>Name</c>, <c>Unit</c>, <c>Instrument</c>, documentation, attributes,
///         examples, and entity associations.</description></item>
/// </list>
/// </summary>
internal static class MetricsEmitter
{
    public static FileWithName Generate(MetricsMarkerModel marker, InstrumentRegistryModel instruments)
    {
        var metrics = ResolveMetrics(instruments, marker.Prefix, marker.Filter);

        var builder = new StringBuilder();
        WriteHeader(builder);
        WriteNamespace(builder, marker.ContainingNamespace);
        WriteClass(builder, marker.ClassName, metrics);

        var fileName = $"{marker.ClassName}.g.cs";
        return new FileWithName(fileName, builder.ToString());
    }

    private static List<MetricDescriptorModel> ResolveMetrics(InstrumentRegistryModel instruments, string prefix, StabilityFilter filter)
    {
        // Stability gating mirrors the contrib/Java/Python "stable package" vs "incubating
        // package" split: under StableOnly we emit only stability=stable rows, under
        // AllStabilities we emit every row (stable + development + release_candidate + ...).
        // Per OTel telemetry-stability.md, deprecated rows stay emitted (with [Obsolete])
        // until upstream drops them — DeprecatedModel is orthogonal to StabilityModel here,
        // so a stable+deprecated row stays under StableOnly while a development+deprecated
        // row only appears under AllStabilities.
        var dotted = prefix + ".";
        var matched = new List<MetricDescriptorModel>();
        foreach (var metric in instruments.Metrics)
        {
            if (!string.Equals(metric.MetricName, prefix, StringComparison.Ordinal) &&
                !metric.MetricName.StartsWith(dotted, StringComparison.Ordinal))
            {
                continue;
            }

            if (!StabilityFiltering.IsIncludedOrDeprecated(metric.Stability, metric.Deprecated, filter))
            {
                continue;
            }

            matched.Add(metric);
        }
        matched.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.MetricName, b.MetricName));
        return matched;
    }

    private static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    private static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    private static void WriteClass(StringBuilder builder, string className, List<MetricDescriptorModel> metrics)
    {
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Constants for metric names and descriptors outlined by the OpenTelemetry specifications.");
        builder.AppendLine("/// </summary>");
        builder.Append("static partial class ").AppendLine(className);
        builder.AppendLine("{");

        var first = true;
        foreach (var metric in metrics)
        {
            if (!first) builder.AppendLine();
            first = false;
            WriteMetricConstant(builder, metric);
        }

        foreach (var metric in metrics)
        {
            builder.AppendLine();
            WriteDescriptorClass(builder, metric);
        }

        builder.AppendLine("}");
    }

    private static void WriteMetricConstant(StringBuilder builder, MetricDescriptorModel metric)
    {
        WriteSummaryComment(builder, metric.Brief, indent: 4);
        WriteObsolete(builder, metric.Deprecated, indent: 4);

        var memberName = MetricMemberName(metric.MetricName);
        builder.Append("    public const string ").Append(memberName)
               .Append(" = \"").Append(metric.MetricName).AppendLine("\";");
    }

    private static void WriteDescriptorClass(StringBuilder builder, MetricDescriptorModel metric)
    {
        WriteSummaryComment(builder, metric.Brief, indent: 4);
        if (!string.IsNullOrEmpty(metric.Note))
            WriteRemarksComment(builder, metric.Note, indent: 4);
        WriteObsolete(builder, metric.Deprecated, indent: 4);

        var descriptorName = DescriptorClassName(metric.MetricName);
        builder.Append("    public static partial class ").AppendLine(descriptorName);
        builder.AppendLine("    {");
        builder.Append("        public const string Name = \"").Append(metric.MetricName).AppendLine("\";");
        builder.Append("        public const string Unit = \"").Append(EscapeForLiteral(metric.Unit)).AppendLine("\";");
        builder.Append("        public const string Instrument = \"").Append(EscapeForLiteral(metric.Instrument)).AppendLine("\";");
        builder.Append("        public const string RequirementLevel = \"")
               .Append(RequirementLevelName(metric.MetricRequirementLevel.Kind)).AppendLine("\";");
        if (!string.IsNullOrEmpty(metric.MetricRequirementLevel.Condition))
        {
            builder.Append("        public const string RequirementCondition = \"")
                   .Append(EscapeForLiteral(metric.MetricRequirementLevel.Condition)).AppendLine("\";");
        }
        builder.Append("        public const string Brief = \"").Append(EscapeForLiteral(metric.Brief)).AppendLine("\";");
        builder.Append("        public const string Note = \"").Append(EscapeForLiteral(metric.Note)).AppendLine("\";");
        builder.AppendLine();
        WriteDescriptorAttributes(builder, metric);
        WriteEntityAssociations(builder, metric);
        builder.AppendLine("    }");
    }

    private static void WriteDescriptorAttributes(StringBuilder builder, MetricDescriptorModel metric)
    {
        builder.Append("        public const int AttributeCount = ").Append(metric.Attributes.Length).AppendLine(";");

        foreach (var attr in metric.Attributes)
        {
            var name = "Attribute" + ToPascalCase(attr.Key);
            builder.Append("        public const string ").Append(name)
                   .Append(" = \"").Append(EscapeForLiteral(attr.Key)).AppendLine("\";");
            builder.Append("        public const string ").Append(name).Append("RequirementLevel")
                   .Append(" = \"").Append(RequirementLevelName(attr.RequirementLevel.Kind)).AppendLine("\";");

            if (!string.IsNullOrEmpty(attr.RequirementLevel.Condition))
            {
                builder.Append("        public const string ").Append(name).Append("RequirementCondition")
                       .Append(" = \"").Append(EscapeForLiteral(attr.RequirementLevel.Condition)).AppendLine("\";");
            }

            if (!string.IsNullOrEmpty(attr.Note))
            {
                builder.Append("        public const string ").Append(name).Append("Note")
                       .Append(" = \"").Append(EscapeForLiteral(attr.Note)).AppendLine("\";");
            }

            WriteExampleConstants(builder, name, attr.Examples);
        }
    }

    private static void WriteExampleConstants(
        StringBuilder builder,
        string memberPrefix,
        EquatableArray<string> examples)
    {
        if (examples.Length == 0)
            return;

        builder.Append("        public const int ").Append(memberPrefix).Append("ExampleCount = ")
               .Append(examples.Length).AppendLine(";");
        for (var i = 0; i < examples.Length; i++)
        {
            builder.Append("        public const string ").Append(memberPrefix).Append("Example")
                   .Append(i + 1).Append(" = \"").Append(EscapeForLiteral(examples[i])).AppendLine("\";");
        }
    }

    private static void WriteEntityAssociations(StringBuilder builder, MetricDescriptorModel metric)
    {
        builder.AppendLine();
        builder.Append("        public const int EntityAssociationCount = ").Append(metric.EntityAssociations.Length).AppendLine(";");

        foreach (var entity in metric.EntityAssociations)
        {
            builder.Append("        public const string EntityAssociation").Append(ToPascalCase(entity))
                   .Append(" = \"").Append(EscapeForLiteral(entity)).AppendLine("\";");
        }
    }

    private static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </summary>");
    }

    private static void WriteRemarksComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <remarks>");
        foreach (var line in SplitLines(text))
        {
            AppendDocLine(builder, pad, line);
        }
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    private static void AppendDocLine(StringBuilder builder, string pad, string line)
    {
        builder.Append(pad).Append("///");
        if (!string.IsNullOrEmpty(line))
            builder.Append(' ').Append(line);
        builder.AppendLine();
    }

    private static void WriteObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        if (deprecated is null) return;

        var pad = new string(' ', indent);
        var message = deprecated switch
        {
            DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
            DeprecatedModel.Obsoleted => "Removed, no replacement.",
            DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
            _ => "Deprecated."
        };
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeForAttribute(message)).AppendLine("\")]");
    }

    internal static string MetricMemberName(string metricName) => "Metric" + ToPascalCase(metricName);

    internal static string DescriptorClassName(string metricName) => ToPascalCase(metricName) + "Descriptor";

    private static string RequirementLevelName(RequirementLevelKind kind) => kind switch
    {
        RequirementLevelKind.Required => "required",
        RequirementLevelKind.Recommended => "recommended",
        RequirementLevelKind.OptIn => "opt_in",
        RequirementLevelKind.ConditionallyRequired => "conditionally_required",
        _ => "unspecified"
    };

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    private static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;

        foreach (var line in text.Split('\n'))
        {
            yield return line.TrimEnd('\r');
        }
    }

    private static string EscapeForLiteral(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", string.Empty);

    private static string EscapeForAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);
}
