// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file is auto-generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2'. Do not edit.</auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace OpenTelemetry.SemanticConventions.Incubating;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class CpythonAttributes
{
    /// <summary>
    /// Value of the garbage collector collection generation.
    /// </summary>
    public const string AttributeCpythonGcGeneration = "cpython.gc.generation";

    /// <summary>
    /// Value of the garbage collector collection generation.
    /// </summary>
    public static class CpythonGcGenerationValues
    {
        /// <summary>
        /// Generation 0.
        /// </summary>
        public const int Generation0 = 0;

        /// <summary>
        /// Generation 1.
        /// </summary>
        public const int Generation1 = 1;

        /// <summary>
        /// Generation 2.
        /// </summary>
        public const int Generation2 = 2;
    }
}
