// <auto-generated/>
// Minimal value-equality polyfills used by the incremental generator pipeline.
// Roslyn IIncrementalGenerator requires equatable pipeline values for caching to
// work; the framework BCL ImmutableArray/Array do not implement value-based
// Equals. EquatableArray<T> and FileWithName below carry only the surface this
// generator consumes; richer LINQ overloads were intentionally omitted to keep
// the maintainer review surface small.
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace OpenTelemetry.SemanticConventions.SourceGeneration;

/// <summary>
/// Immutable, value-equality array used as a pipeline-cacheable input/output
/// for Roslyn incremental generators. Elements must themselves have value
/// equality (records, primitives) for the equality contract to hold.
/// </summary>
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>, IReadOnlyList<T>
    where T : IEquatable<T>
{
    public static readonly EquatableArray<T> Empty = new(Array.Empty<T>());

    private readonly T[] _items;

    public EquatableArray(T[] items)
    {
        _items = items ?? Array.Empty<T>();
    }

    // Null-safe accessor: default(EquatableArray<T>) has _items == null.
    // Treat it as empty so downstream emitters never see an NRE through
    // record-struct positional parameters.
    private T[] Items => _items ?? Array.Empty<T>();

    public int Count => this.Items.Length;

    public int Length => this.Items.Length;

    public bool IsEmpty => this.Items.Length == 0;

    public T this[int index] => this.Items[index];

    public bool Equals(EquatableArray<T> other)
    {
        var left = this.Items;
        var right = other.Items;
        if (left.Length != right.Length)
        {
            return false;
        }

        for (var i = 0; i < left.Length; i++)
        {
            if (!left[i].Equals(right[i]))
            {
                return false;
            }
        }

        return true;
    }

    public override bool Equals(object? obj) =>
        obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            foreach (var item in this.Items)
            {
                hash = hash * 31 + item.GetHashCode();
            }

            return hash;
        }
    }

    public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)this.Items).GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => this.Items.GetEnumerator();

    public static bool operator ==(EquatableArray<T> left, EquatableArray<T> right) =>
        left.Equals(right);

    public static bool operator !=(EquatableArray<T> left, EquatableArray<T> right) =>
        !left.Equals(right);
}

internal static class EquatableArrayExtensions
{
    public static EquatableArray<T> ToEquatableArray<T>(this IEnumerable<T> source)
        where T : IEquatable<T> =>
        new(source as T[] ?? source.ToArray());
}

/// <summary>
/// Filters out null entries from an incremental values provider so the
/// downstream pipeline can rely on non-null values without separate null
/// checks at every consumer. Mirrors the convenience helper that
/// IIncrementalGenerator pipelines commonly inline.
/// </summary>
internal static class IncrementalValuesProviderExtensions
{
    public static IncrementalValuesProvider<T> WhereNotNull<T>(
        this IncrementalValuesProvider<T?> source)
        where T : struct =>
        source.Where(static x => x.HasValue).Select(static (x, _) => x!.Value);
}

/// <summary>
/// Pair of (file hint name, source text) returned by emitters. Value-equality
/// so the generator pipeline can cache it.
/// </summary>
internal readonly record struct FileWithName(string Name, string Text)
{
    public static FileWithName Empty => new(string.Empty, string.Empty);

    public bool IsEmpty => string.IsNullOrEmpty(Name) || string.IsNullOrEmpty(Text);
}
