// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using OpenTelemetry.SemanticConventions.SourceGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;
using OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;

namespace OpenTelemetry.SemanticConventions.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class SemConvActivitiesGenerator : IIncrementalGenerator
{
    internal const string StableAttributeFullName =
        "OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionActivitiesAttribute";

    internal const string IncubatingAttributeFullName =
        "OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionIncubatingActivitiesAttribute";

    internal const string AttributeFullName = StableAttributeFullName;

    private const string StableAttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace OpenTelemetry.SemanticConventions.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.Conditional("QYL_SEMCONV_USAGES")]
        internal sealed class SemanticConventionActivitiesAttribute : global::System.Attribute
        {
            public SemanticConventionActivitiesAttribute(string prefix)
            {
                Prefix = prefix;
            }

            public string Prefix { get; }
        }
        """;

    private const string IncubatingAttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace OpenTelemetry.SemanticConventions.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.Conditional("QYL_SEMCONV_USAGES")]
        internal sealed class SemanticConventionIncubatingActivitiesAttribute : global::System.Attribute
        {
            public SemanticConventionIncubatingActivitiesAttribute(string prefix)
            {
                Prefix = prefix;
            }

            public string Prefix { get; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SemanticConventionActivitiesAttribute.g.cs", StableAttributeSource);
            ctx.AddSource("SemanticConventionIncubatingActivitiesAttribute.g.cs", IncubatingAttributeSource);
        });

        var stableMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                StableAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ActivitiesMarkerExtractor.Extract(ctx, StabilityFilter.StableOnly, ct))
            .WhereNotNull();

        var incubatingMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                IncubatingAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ActivitiesMarkerExtractor.Extract(ctx, StabilityFilter.AllStabilities, ct))
            .WhereNotNull();

        context.RegisterSourceOutput(stableMarkers, static (spc, marker) =>
        {
            var file = ActivityExtensionsEmitter.Generate(marker, ActivityRegistryLoader.Registry);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });

        context.RegisterSourceOutput(incubatingMarkers, static (spc, marker) =>
        {
            var file = ActivityExtensionsEmitter.Generate(marker, ActivityRegistryLoader.Registry);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });
    }
}
