name: 'Assign Reviewers'
on:
  # pull_request_target is suggested for projects where pull requests will be
  # made from forked repositories. If pull_request is used in these cases,
  # the github token will not have sufficient permission to update the PR.
  pull_request_target: # zizmor: ignore[dangerous-triggers] No user code is executed

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  assign:
    name: Assign Reviewers
    permissions:
      pull-requests: write # Required for assigning reviewers to PRs
    runs-on: ubuntu-24.04
    steps:
      - uses: dyladan/component-owners@7ff2b343629407c4dbe1c28ae66f55f723543d2b # v0.2.0
        with:
          assign-owners: ${{ github.event.pull_request.draft == false }}
          request-owner-reviews: ${{ github.event.pull_request.draft == false }}
