name: Live Integration Build OpenTelemetry.Exporter.OneCollector

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build-live-integration-test:
    strategy:
      fail-fast: false
      matrix:
        os:
        # renovate: datasource=github-runners depType=github-runner
        - ubuntu-24.04
        # renovate: datasource=github-runners depType=github-runner
        - windows-2025
        version: [ net462, net10.0, net11.0 ]
        exclude:
        - os: ubuntu-24.04
          version: net462
    uses: ./.github/workflows/integration-test-reusable.yml
    with:
      component: OpenTelemetry.Exporter.OneCollector
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      test-filter: OneCollectorIntegrationTests
      env-var-name: OTEL_ONECOLLECTOR_INSTRUMENTATION_KEY
    secrets:
      instrumentation-key: ${{ secrets.OTEL_ONECOLLECTOR_INSTRUMENTATION_KEY }}
