name: build-test

on:
  push:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths:
      - 'modules/Resources.OperatingSystem/**'
      - '.github/workflows/ci-Resources.OperatingSystem.yml'
  pull_request:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths:
      - 'modules/Resources.OperatingSystem/**'
      - '.github/workflows/ci-Resources.OperatingSystem.yml'

jobs:
  resources-operatingsystem:
    uses: ./.github/workflows/build-module.yml
    with:
      module-name: Resources.OperatingSystem
      module-directory: "modules/Resources.OperatingSystem"

  _resources-operatingsystem:
    uses: ./.github/workflows/deploy-module.yml
    if: ${{ github.event_name == 'push' }}
    with:
      module-name: Resources.OperatingSystem
      module-directory: "modules/Resources.OperatingSystem"

  build-test:
    needs: [
      resources-operatingsystem,
      _resources-operatingsystem
    ]
    if: always() && !cancelled()
    runs-on: ubuntu-22.04
    steps:
    - run: |
          if ( ${{ contains(needs.*.result, 'failure') }} == true ); then echo 'build failed ✗'; exit 1; else echo 'build complete ✓'; fi
