name: Core version update

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release tag'
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.tag }}
  cancel-in-progress: false

jobs:
  automation:
    uses: ./.github/workflows/automation.yml
    secrets:
      OTELBOT_DOTNET_CONTRIB_PRIVATE_KEY: ${{ secrets.OTELBOT_DOTNET_CONTRIB_PRIVATE_KEY }}

  core-version-update:
    name: Update core package versions
    runs-on: ubuntu-24.04

    needs: automation

    if: needs.automation.outputs.enabled

    steps:
    - name: Generate GitHub App token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: otelbot-token
      with:
        client-id: ${{ vars.OTELBOT_DOTNET_CONTRIB_APP_ID }}
        private-key: ${{ secrets.OTELBOT_DOTNET_CONTRIB_PRIVATE_KEY }}
        permission-contents: write
        permission-pull-requests: write

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: true # zizmor: ignore[artipacked] Needed to push commits
        ref: ${{ github.event.repository.default_branch }}
        show-progress: false
        token: ${{ steps.otelbot-token.outputs.token }}

    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0

    - name: Create GitHub Pull Request to update core version in props and update CHANGELOGs in projects
      shell: pwsh
      env:
        GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
        BOT_USER_EMAIL: ${{ needs.automation.outputs.email }}
        BOT_USER_NAME: ${{ needs.automation.outputs.username }}
        TARGET_BRANCH: ${{ github.event.repository.default_branch }}
        TAG: ${{ inputs.tag }}
      run: |
        Import-Module .\build\scripts\post-release.psm1

        CreateOpenTelemetryCoreLatestVersionUpdatePullRequest `
          -gitRepository ${env:GITHUB_REPOSITORY} `
          -tag ${env:TAG} `
          -targetBranch ${env:TARGET_BRANCH} `
          -gitUserName ${env:BOT_USER_NAME} `
          -gitUserEmail ${env:BOT_USER_EMAIL}
