name: Dependency Submission (NuGet)

on:
  push:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
  submit-nuget:
    name: Submit NuGet dependency snapshot
    if: github.event.repository.fork == false
    runs-on: windows-2025
    timeout-minutes: 10

    permissions:
      contents: write # Submit the generated dependency snapshot to the repository dependency graph
      id-token: write # Authenticate the dependency submission with GitHub OIDC

    steps:
      - name: Update agent configuration
        shell: pwsh
        run: |
          "DOTNET_INSTALL_DIR=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "DOTNET_ROOT=D:\tools\dotnet" >> ${env:GITHUB_ENV}
          "NUGET_PACKAGES=D:\.nuget\packages" >> ${env:GITHUB_ENV}

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Component detection
        uses: advanced-security/component-detection-dependency-submission-action@b876b8cc341a53970394b33ea0ca4e86c25542de # v0.1.3
        with:
          detectorsCategories: NuGet
