name: Pack

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
    - cron: '0 0 * * *' # once in a day at 00:00
  push:
    tags:
      - '*' # trigger when we create a tag       

jobs:
  build-test-pack:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetching all

    - name: Install dependencies
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore -p:Deterministic=true

    - name: dotnet pack
      run: dotnet pack opentelemetry-dotnet-contrib.proj --configuration Release --no-build

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-packages
        path: '**/bin/**/*.*nupkg'
