name: .NET Linux

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [netcoreapp2.1,netcoreapp3.1]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test ${{ matrix.version }}
      run: dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll
