name: .NET

on:
  push:
    branches: [ master ]
    tags:
    - '*'
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'

jobs:
  build-test-pack:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetching all

    - name: Install dependencies
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore -p:Deterministic=true

    - name: dotnet test
      run: dotnet test -p:CollectCoverage=false --configuration Release --no-build --logger:"console;verbosity=detailed"

    - name: dotnet pack
      if: ${{ matrix.os == 'windows-latest' }}
      run: dotnet pack opentelemetry-dotnet-contrib.proj --configuration Release --no-build

    - name: Publish Artifacts
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-packages
        path: '**/bin/**/*.*nupkg'
