name: Build Component [Pre]

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      module-directory:
        required: false
        default: '.'
        type: string

jobs:
  run-dotnet-format:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        working-directory: '${{ inputs.module-directory }}'

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup dotnet
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1

    - name: dotnet restore ${{ inputs.module-name }}
      run: dotnet restore

    - name: dotnet format ${{ inputs.module-name }}
      run: dotnet format --no-restore --verify-no-changes

    - name: dotnet build ${{ inputs.module-name }}
      run: dotnet build --configuration Release --no-restore

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          **/bin
          **/obj
        retention-days: 1
