name: Build Component [Post]

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      module-directory:
        required: false
        default: '.'
        type: string
      pack:
        default: true
        required: false
        type: boolean

jobs:
  run-dotnet-pack:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        working-directory: '${{ inputs.module-directory }}'

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup dotnet
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1

    - name: dotnet restore ${{ inputs.module-name }}
      run: dotnet restore

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: dotnet pack ${{ inputs.module-name }}
      if: ${{ inputs.pack }}
      run: dotnet pack --configuration Release --no-restore --no-build -p:EnablePackageValidation=true

    - name: Publish ${{ inputs.module-name }} NuGet packages to Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      # Only publish packages from the first job
      if: ${{ inputs.pack && strategy.job-index == 0 }}
      with:
        name: ${{ inputs.module-name }}-packages
        path: '.\modules\**\src\**\*.*nupkg'
        if-no-files-found: error
