name: Code Coverage

on:
  push:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths-ignore:
    - '**.md'
    - '*/OpenTelemetry.Instrumentation.Process*/**'
    - '*/OpenTelemetry.Exporter.OneCollector*/**'
  pull_request:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths-ignore:
    - '**.md'
    - '*/OpenTelemetry.Instrumentation.Process*/**'
    - '*/OpenTelemetry.Exporter.OneCollector*/**'

jobs:
  build-test-report:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Install dependencies
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore

    - name: dotnet test
      run: dotnet test --collect:"Code Coverage" --results-directory:"TestResults" --configuration Release --no-restore --no-build -- RunConfiguration.DisableAppDomain=true

    - name: Install coverage tool
      run: dotnet tool install -g dotnet-coverage

    - name: Merging test results
      run: dotnet-coverage merge -r -f cobertura -o ./TestResults/Cobertura.xml ./TestResults/*.coverage

    - uses: codecov/codecov-action@v3.1.4
      env:
        OS: ${{ matrix.os }}
      with:
        file: TestResults/Cobertura.xml
        env_vars: OS
        flags: unittests
        name: Code Coverage for ${{ matrix.os }}
