name: Code Coverage

on:
  push:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths-ignore:
    - '**.md'
    - '*/OpenTelemetry.Instrumentation.Process*/**'
    - '*/OpenTelemetry.Exporter.OneCollector*/**'
  pull_request:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]
    paths-ignore:
    - '**.md'
    - '*/OpenTelemetry.Instrumentation.Process*/**'
    - '*/OpenTelemetry.Exporter.OneCollector*/**'

jobs:
  build-test-report:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetching all

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test ${{ matrix.version }}
      run: dotnet test **/bin/Release/${{ matrix.version }}/*.Tests.dll --collect:"Code Coverage" --results-directory:"TestResults" --framework ${{ matrix.version }} --logger:"console;verbosity=detailed" -- RunConfiguration.DisableAppDomain=true

    - name: Install coverage tool
      run: dotnet tool install -g dotnet-coverage

    - name: Merging test results
      run: dotnet-coverage merge -r -f cobertura -o ./TestResults/Cobertura.xml ./TestResults/*.coverage

    - uses: codecov/codecov-action@v3.1.4
      env:
        OS: ${{ matrix.os }}
        TFM: ${{ matrix.version }}
      with:
        file: TestResults/Cobertura.xml
        env_vars: OS,TFM
        flags: unittests
        name: Code Coverage for solution on [${{ matrix.os }}.${{ matrix.version }}]
