name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  fossa:
    name: Run FOSSA scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    if: github.event.repository.fork == false
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Run FOSSA analysis
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # v2.0.0
        if: env.FOSSA_API_KEY != ''
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          team: OpenTelemetry
