name: Pack OpenTelemetry.Instrumentation.SqlClient

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.SqlClient-*' # trigger when we create a tag with prefix "Instrumentation.SqlClient-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Instrumentation.SqlClient
    secrets: inherit
