name: Pack OpenTelemetry.Instrumentation.AspNet

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.AspNet-*' # trigger when we create a tag with prefix "Instrumentation.AspNet-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Instrumentation.AspNet
    secrets: inherit
