name: Pack OpenTelemetry.ResourceDetectors.Gcp

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'ResourceDetectors.Gcp-*' # trigger when we create a tag with prefix "ResourceDetectors.Gcp-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.ResourceDetectors.Gcp
    secrets: inherit
