name: Pack OpenTelemetry.Instrumentation.Http

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Http-*' # trigger when we create a tag with prefix "Instrumentation.Http-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Instrumentation.Http
    secrets: inherit
