name: Pack OpenTelemetry.Exporter.Geneva

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Exporter.Geneva-*' # trigger when we create a tag with prefix "Exporter.Geneva-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Exporter.Geneva
    secrets: inherit
