name: Pack OpenTelemetry.Instrumentation.Owin

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Owin-*' # trigger when we create a tag with prefix "Instrumentation.Owin-"

jobs:
  call-build-test-pack:
    permissions:
      contents: write
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Instrumentation.Owin
    secrets: inherit
