name: Pack OpenTelemetry.Resources.Gcp

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Resources.Gcp-*' # trigger when we create a tag with prefix "Resources.Gcp-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project-name: OpenTelemetry.Resources.Gcp
    secrets: inherit
