name: Publish & Verify AOT Compatibility

on:
  workflow_call:

jobs:
  run-verify-aot-compat:

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ net8.0 ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: publish AOT testApp, assert static analysis warning count, and run the app
      shell: pwsh
      run: .\build\scripts\test-aot-compatibility.ps1 ${{ matrix.version }}
