name: Lint - YAML

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-yamllint:
    name: Run yamllint
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Run yamllint
      run: yamllint --no-warnings .
